import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Github, Linkedin, Mail, Phone, MapPin, ArrowUpRight, Download, Code2, Database, Server, Sparkles, Menu, X, Send, CheckCircle2} from 'lucide-react';
import './styles.css';

const projects=[
 {title:'Personal AI Assistant',tag:'AI Agent • Full-Stack',stack:'Next.js • OpenAI Responses API • Web Search • PWA • GitHub API',text:'Private, mobile-friendly personal AI agent with persistent memory, tasks/reminders, web search, file uploads, optional GitHub access and browser speech-to-text.',metric:'AI + automation',icon:'✦',url:'https://github.com/adarshdixit989/personal-ai-assistant'},
 {title:'DataStream Pro',tag:'Enterprise Real-Time Analytics Platform',stack:'Python • Django • Apache Kafka • Redis • Docker • PostgreSQL • AWS • Scikit-learn',text:'Distributed microservices analytics platform processing 1M+ streaming events daily, with ML-driven anomaly detection and forecasting.',metric:'1M+ events/day',icon:'◈',url:'https://github.com/adarshdixit989/datastream-pro'},
 {title:'BankEase',tag:'Banking Management System',stack:'Java • Spring Boot • MySQL • REST APIs • JWT',text:'Secure banking system supporting account creation, transactions and fund transfers with JWT authentication and role-based access control.',metric:'Secure REST architecture',icon:'₿',url:'#'},
 {title:'Krishi Neuron',tag:'AI Agriculture Assistant',stack:'React • Express.js • ML Models • APIs',text:'AI-powered agriculture assistant for crop recommendations, disease detection and price prediction with an interactive farmer dashboard.',metric:'AI + full-stack',icon:'🌱',url:'https://github.com/adarshdixit989/KrishiNeuron'},
 {title:'NewsMonkey',tag:'React News App',stack:'React • JavaScript • Bootstrap • REST APIs • News API',text:'Responsive news platform with category filters, infinite scrolling and optimized rendering for high-volume API usage.',metric:'10K+ API requests/day',icon:'⌁',url:'#'},
 {title:'Adarsh Portfolio',tag:'This website • Full-Stack',stack:'React • TypeScript • FastAPI • PostgreSQL • Docker',text:'Recruiter-focused portfolio with responsive UI, API-backed contact form, PostgreSQL persistence and Dockerized development.',metric:'This website',icon:'AD',url:'https://github.com/adarshdixit989/PROTFOLIO'}
];
const skills=['Java','Python','TypeScript','JavaScript','React','HTML','CSS','Spring Boot','Flask','Express.js','REST APIs','MySQL','SQL','Git','GitHub','Docker','PostgreSQL','Apache Kafka','Redis','AWS','Scikit-learn','DSA','OOP','Agile/Scrum','Debugging'];
const experience=[['Web Developer Intern','CodeSoft','Jun 2024 – Jul 2024','Built reusable responsive React UI components, integrated/tested REST APIs, improved performance and cross-browser compatibility, and collaborated in Agile workflows.'],['Java Trainee','Codules','Sep 2024 – Oct 2024','Completed intensive Java training in Core Java, OOP, DSA and JDBC; developed and debugged console/GUI applications and strengthened analytical skills.']];

function App(){
 const [open,setOpen]=useState(false); const [sent,setSent]=useState(false); const [form,setForm]=useState({name:'',email:'',subject:'',message:''});
 const submit=async(e:React.FormEvent)=>{e.preventDefault(); try{const r=await fetch((import.meta.env.VITE_API_URL||'http://localhost:8000')+'/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); if(!r.ok) throw new Error(); setSent(true);setForm({name:'',email:'',subject:'',message:''})}catch{setSent(false);alert('Backend unavailable. Start the FastAPI service and try again.')}};
 const nav=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setOpen(false)};
 return <div className="site">
  <header className="nav"><div className="brand"><span className="brand-dot"/>AD<span>.</span></div><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{['about','experience','projects','skills','contact'].map(x=><button key={x} onClick={()=>nav(x)}>{x}</button>)}<a href="/Adarsh-Dixit-Resume.pdf" download className="resume"><Download size={15}/> Resume</a></nav></header>
  <main>
   <section className="hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={16}/> AVAILABLE FOR SOFTWARE / FULL-STACK OPPORTUNITIES</div><h1>Building software<br/><span>that works.</span></h1><p className="lead">I'm <b>Adarsh Dixit</b>, a Computer Science graduate who enjoys turning complex problems into reliable, scalable and well-tested products.</p><div className="actions"><button className="primary" onClick={()=>nav('projects')}>Explore my work <ArrowUpRight size={17}/></button><button className="ghost" onClick={()=>nav('contact')}>Let's connect <Mail size={16}/></button></div><div className="social"><a href="https://github.com/adarshdixit989" target="_blank" rel="noreferrer"><Github/></a><a href="https://www.linkedin.com/in/adarsh-dixit9" target="_blank" rel="noreferrer"><Linkedin/></a><a href="mailto:adarshdixit998@gmail.com"><Mail/></a></div></div><div className="hero-card"><div className="grid-art"><div className="code-pill">&lt;developer /&gt;</div><img className="profile-photo" src="/adarsh-profile.jpg" alt="Adarsh Dixit"/><div className="mini-card"><Code2 size={17}/><span>Full-Stack</span></div><div className="mini-card second"><Database size={17}/><span>Data & APIs</span></div></div></div></section>
   <section className="stats"><div><strong>6</strong><span>Featured projects</span></div><div><strong>1M+</strong><span>Streaming events/day</span></div><div><strong>99.9%</strong><span>Platform uptime</span></div><div><strong>30%</strong><span>ML decision accuracy gain</span></div></section>
   <section id="about" className="section split"><div><p className="kicker">01 / ABOUT</p><h2>Curious by nature.<br/><em>Practical by craft.</em></h2></div><div className="copy"><p>Detail-oriented Computer Science graduate with a strong foundation in Java, Python, data structures and algorithms, plus hands-on experience across the software development lifecycle.</p><p>I bring a quality-first mindset to development: debugging deeply, testing APIs, collaborating in Agile teams, and building maintainable full-stack applications.</p><div className="facts"><span><MapPin size={16}/> Greater Noida, India</span><span><Mail size={16}/> adarshdixit998@gmail.com</span><span><Phone size={16}/> +91 9569522432</span></div></div></section>
   <section id="experience" className="section"><p className="kicker">02 / EXPERIENCE</p><h2>Where I've <em>learned by building.</em></h2><div className="timeline">{experience.map((e,i)=><article className="timeline-item" key={e[0]}><div className="timeline-dot">0{i+1}</div><div><div className="role-row"><h3>{e[0]}</h3><span>{e[2]}</span></div><p className="company">{e[1]}</p><p>{e[3]}</p></div></article>)}</div></section>
   <section id="projects" className="section projects"><p className="kicker">03 / SELECTED WORK</p><div className="section-head"><h2>Projects with <em>purpose.</em></h2><span>6 projects · Built, tested & documented</span></div><div className="project-grid">{projects.map((p,i)=><article className="project" key={p.title}><div className="project-top"><span className="project-icon">{p.icon}</span><span className="number">0{i+1}</span></div><h3>{p.title}</h3><h4>{p.tag}</h4><p>{p.text}</p><div className="stack">{p.stack}</div><div className="project-foot"><span>{p.metric}</span>{p.url!=='#'?<a href={p.url} target="_blank" rel="noreferrer"><ArrowUpRight size={17}/></a>:<span title="GitHub link to be added"><ArrowUpRight size={17}/></span>}</div></article>)}</div></section>
   <section id="skills" className="section skills"><p className="kicker">04 / TOOLKIT</p><h2>My technical <em>toolbox.</em></h2><div className="skill-wrap">{skills.map(s=><span key={s}>{s}</span>)}</div><div className="skill-columns"><div><Server/><h3>Engineering</h3><p>STLC & SDLC fundamentals, OOP, DSA, debugging, problem solving and scalable application design.</p></div><div><Database/><h3>Data & Backend</h3><p>REST APIs, relational databases, MySQL, PostgreSQL, JDBC, Kafka, Redis and service architecture.</p></div><div><Code2/><h3>Delivery</h3><p>Git/GitHub, Docker, AWS, Agile/Scrum, version control and cross-browser compatibility.</p></div></div></section>
   <section className="section education"><div><p className="kicker">05 / EDUCATION</p><h2>Computer Science<br/><em>foundation.</em></h2></div><div className="edu-card"><span>Sep 2022 – Jul 2026</span><h3>B.Tech in Computer Science</h3><p>Mangalmay Institute of Engineering and Technology, Greater Noida</p><b>Class Representative</b></div></section>
   <section id="contact" className="section contact"><div><p className="kicker">06 / CONTACT</p><h2>Have a project or<br/><em>opportunity?</em></h2><p className="contact-copy">I'm open to software developer, full-stack and engineering opportunities. Send a message and let's start a conversation.</p></div><form onSubmit={submit}>{sent&&<div className="sent"><CheckCircle2 size={17}/> Message submitted successfully.</div>}<div className="two"><input required placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" placeholder="Email address" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><input required placeholder="Subject" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><textarea required placeholder="Tell me about it..." rows={6} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><button className="primary" type="submit">Send message <Send size={16}/></button></form></section>
  </main><footer><div className="brand">AD<span>.</span></div><p>© 2026 Adarsh Dixit. Built with React, TypeScript & FastAPI.</p><a href="mailto:adarshdixit998@gmail.com">adarshdixit998@gmail.com</a></footer>
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);